### ISSUE TITLE
Enable Travis-CI and coveralls.io

### ISSUE THREAD

**Issue by geowurster** [click-contrib/click-plugins#3]
@untitaker looks like owners are the only ones that can enable Travis and coveralls.  I requested access for coveralls but I didn't see `click-plugins` anywhere in Travis.  When you get a chance, and assuming you're ok with both of these services, could you enable them?

**Comment by untitaker** [comment]
I've enabled both now, I think.

**Comment by geowurster** [comment]
@untitaker Looks like an admin has to check the box at Travis to enable the service at the repo level too.  I think coveralls is good to go but won't know for sure until I get a Travis build that triggers coveralls.

**Comment by untitaker** [comment]
https://travis-ci.org/click-contrib/click-plugins shows a successful build?

**Comment by untitaker** [comment]
I've removed your screenshot because it contained a Travis token (I think?)

http://blog.travis-ci.com/2013-01-28-token-token-token/

**Comment by geowurster** [comment]
Ah yep I had a bad badge URL in the readme.  Good call about the token.  Thanks for getting these set up!
