### ISSUE TITLE
"show_envvar=True" inside plugins shows . used in environment variable name

### ISSUE THREAD

**Issue by heeplr** [click-contrib/click-plugins#36]
It seems that plugin names are not properly massaged for use as environment variable names. This conflicts with plugins that have a dot in their name:

```
entry_points={
  "my_plugins": [
    "plugin.foo=myproject.plugins.foo:foo_cmd"
  ]
}
```
the help text for a parameter "bar" shows "MYPROJECT_PLUGIN.FOO_BAR" which is an invalid envvar name in most environments.

I'm not sure if this is actually a [click issue](https://github.com/pallets/click/blob/main/src/click/core.py#L410) so I'm asking here first for a fix or clarification.

**Comment by geowurster** [comment]
@heeplr this is not enough information for me to assess whether or not this is a `click-plugins` problem. However, `click-plugins` just loads a registered object, so I highly suspect this is related to how your plugin command and option are configured, or it is a `click` issue. I was unable to quickly recreate the behavior locally with a bit of targeted testing.
